### ISSUE TITLE
Use of global?

### ISSUE THREAD

**Issue by gahjelle** [CodeClub/python-curriculum#24]
This may be something that has already been discussed(?), but I am somewhat skeptical to the introduction of global in lesson 6 and later. In general, I feel that it is too easy to do bad stuff with global unless you know what you are doing, and that we might be better off never introducing it to the kids?

Unfortunately, the callback methods in Tkinter essentially require you to do either globals or classes (or even weirder things). However, by using the mutable list `grid` to keep state in lesson 6 and 7 we can get away with never introducing either of them. This abuses some fairly subtle things (local/global scope, immutability/mutability) though, and could cause some confusion for kids who want to try stuff on their own.

I have examples (in Norwegian, but the code should be readable) that avoid global in branches (06No and 07No) at my fork: https://github.com/gahjelle/python-curriculum

For lesson 8 (neat game by the way) one could possibly introduce classes as a means of organizing code? This could tie in quite nicely with what the kids have already learned in Scratch: That code belongs to different "sprites". Does anybody already have any experience with this?

Best,
Geir Arne

**Comment by CodeClubRik** [comment]
I'm closing this issue, as it relates to what is now an archived project.
Please feel free to re-open this issue if you want to discuss again.
