### ISSUE TITLE
Python code not rendering properly

### ISSUE THREAD

**Issue by CodeClubRik** [CodeClub/python-curriculum#38]
I have no idea why this code (in the hangman project) isn't rendering properly... it's no different from other code blocks, as far as I can tell.

![thumbnail](https://cloud.githubusercontent.com/assets/7372432/5917667/64731aba-a617-11e4-842d-8f0e1a1cdf51.png)

**Comment by andylolz** [comment]
For reference – the relevant markdown is here:
https://github.com/CodeClub/python-curriculum/blob/23b3683a/en-GB/lessons/Hangman/Hangman.md#step-4-track-the-mistakes--activity

**Comment by andylolz** [comment]
This breaks in a surprising way… But the code indentation is wrong in this project (and others, in fact).

**Comment by CodeClubRik** [comment]
thanks andy! does that mean there's an inconsistency between styles for python and other languages?

**Comment by andylolz** [comment]
I’m not sure what you mean. The way the markdown for code blocks should be written isn’t different – the markdown parser doesn’t know the difference between scratch or python.

Currently, several of the python projects have bad indentation. For instance, all of the code snippets in [Minecraft2D](http://projects.codeclub.org.uk/en-GB/06_python/06/Minecraft2D.html) are incorrectly indented. This means you can’t copy/paste code out of that project without first fixing the indentation.

**Comment by CodeClubRik** [comment]
> Currently, several of the python projects have bad indentation.
I hadn't spotted that -- I'll fix that now. Thanks.
