### ISSUE TITLE
PEP 8 code snippets

### ISSUE THREAD

**Issue by andylolz** [CodeClub/python-curriculum#40]
All sorts of stuff works in Python, but that doesn’t mean you should do it! The [PEP 8 Python Style Guide](https://www.python.org/dev/peps/pep-0008/) is excellent for standardising Python code, making it clearer (particularly for beginners). I’d suggest sticking to this style guide for all code snippets in this repo.

To help with this, there are PEP8 linter plugins for most editors.

**Comment by rikcross** [comment]
Thanks @andylolz - I'll close this issue now, but please reopen if you spot anything non-standard.

**Comment by andylolz** [comment]
No worries
