### ISSUE TITLE
OS license?

### ISSUE THREAD

**Issue by eah13** [CodeClub/python-curriculum#41]
It seems like CodeClub's intent is for this content to be open licensed.  This would require an open license of some sort.  @CodeClubRik I imagine you're the one to ask.

MIT is a favorite of ours at Trinket.

**Comment by andylolz** [comment]
Though it’s not mentioned on this source repo, the generated Code Club project material is licensed under a [Creative Commons BY-NC-SA](http://creativecommons.org/licenses/by-nc-sa/4.0/) licence.

I wonder if it’s worth adding this various places… e.g. the end of the README on each source repo, as well as the two project repos.

**Comment by CodeClubRik** [comment]
This has now been done, e.g.:
https://github.com/CodeClub/python-curriculum/blob/new-layout/LICENSE.md
