### ISSUE TITLE
Use of `import *`

### ISSUE THREAD

**Issue by andylolz** [CodeClub/python-curriculum#49]
For learning python, `import *` is confusing, because it makes it impossible to discern what is a built-in and what has been imported. I know that other languages force you to do this, but python doesn’t. So for example:

```python
from random import *
print("You should name your new pet" , choice(["Bob", "Fluffy", "Martin"]))
```

As a newcomer, I can’t tell what `choice` is doing or where it has come from. This is clearer, because at least we’re explicit about what’s imported:

```python
from random import choice
print("You should name your new pet" , choice(["Bob", "Fluffy", "Martin"]))
```

Personally, though, I think this is clearest, since `random.choice` is self-explanatory.

```python
import random
print("You should name your new pet" , random.choice(["Bob", "Fluffy", "Martin"]))
```

I started trying to fix all the instances of this, but there are quite a lot.

**Comment by CodeClubRik** [comment]
Cheers for the feedback @andylolz 

As far as I remember, the reason for using `from [module] import *` was that the turtle projects were much simpler without having to write `turtle.` before every command, and I was trying to cut down on the amount of typing needed. Maybe this wasn't a great idea.

**Comment by andylolz** [comment]
So… In that case, you could do:

```python
from turtle import forward, backward, left, right, shape, speed, done

forward(100)
```

…which at least makes it clear at the top of the program where these commands have come from. Alternatively:

```python
import turtle as t

t.forward(100)
```

**Comment by immunda** [comment]
@andylolz I think importing individual methods/names is explicit enough, but is more clean and concise than using module prefixes everywhere.

Totally agree about avoiding `import *` like the plague.

**Comment by martinpeck** [comment]
Doesn't this rather depend upon the purpose of the import?

If we're teaching kids all about the turtle library, and what it includes, then it makes sense to call out where these things come from more explicitly. If we're using turtle to teach kids about loops then does it require this level of explicitness?

From looking at the two projects that use Turtles, it does appear that we're teaching the kids about the turtle library, so the more explicit imports make some sense, but I'm not sure a blanket rule on using this style of import makes sense - it needs to be weighed up with the learning objective.

**Comment by andylolz** [comment]
> I'm not sure a blanket rule on using this style of import makes sense 

Agreed – I wouldn’t make it a blanket rule, but I would suggest avoiding it (which is also what [the python style guide](https://www.python.org/dev/peps/pep-0008/#imports) suggests).

> From looking at the two projects that use Turtles

`import *` is used in 6 current projects (and a few additional projects). Taking it on a case by case basis is fine. Here they are:

 * [Turtle Power](http://projects.codeclub.org.uk/en-GB/05_python/04/Turtle%20Power.html)
 * [Gameshow](http://projects.codeclub.org.uk/en-GB/05_python/05/Gameshow.html)
 * [Compliment Generator](http://projects.codeclub.org.uk/en-GB/05_python/06/Compliment%20Generator.html)
 * [Teaching Turtles](http://projects.codeclub.org.uk/en-GB/06_python/02/Teaching%20Turtles.html)
 * [Pokedex](http://projects.codeclub.org.uk/en-GB/06_python/04/Pokedex.html)
 * [Minecraft2D](http://projects.codeclub.org.uk/en-GB/06_python/06/Minecraft2D.html)

My original example was from [Compliment Generator](http://projects.codeclub.org.uk/en-GB/05_python/06/Compliment%20Generator.html), and concerned the `random` module. I’ve sent a pull request for that one.

**Comment by andylolz** [comment]
> I actually find using `as` and a shortname can cause more confusion as you've lost the benefit of not leaving the context to go and refer to which package is which in the header.

That’s true… But the prefix does at least still give the reader the queue to go and look in the header. `import *` doesn’t give that, and in fact nor does importing individual methods (though that’s the way I’d usually do it).

**Comment by andylolz** [comment]
I tried changing it for Turtle Power, and it’s really difficult! I think I have come around to your way of thinking on this, @martinpeck.

**Comment by martinpeck** [comment]
Having chatted with @CodeClubRik I think the plan is to `import foo` and then `foo.bar` within the code.

So, for Turtle there'd be a single `import turtle` and then `turtle.forward()` calls within the code. This makes the fact that `forward()` comes from the `turtle` import clearer, without making the import statement super verbose.

**Comment by NDevox** [comment]
Is this something that is going to get updated to `import foo`, `foo.bar` type usage?

I would side with the opinion that explicit imports are better for these projects. And if an update is planned I'm happy to do the work.

**Comment by CodeClubRik** [comment]
Hi @NDevox, yes the plan is to update to explicit imports, although it's not a high priority. There are some other changes planned too, such as the move to using [Trinket](https://trinket.io) for writing Python programs online. As screenshots will also need updating, I think it makes sense to make these changes together.

**Comment by rik-cross** [comment]
The [new python projects](https://codeclubprojects.org/en-GB/python/) have implemented `import x` in place of `from x import *`.

The exception is the use of the turtle module. Projects that make use of the turtle use it a _lot_, and it was felt that the repeated `turtle.x` syntax created too much additional typing, and took focus away from the learning outcomes of the project.
