### ISSUE TITLE
RPG and Minecraft2D Python code formatting

### ISSUE THREAD

**Issue by CodeClubRik** [CodeClub/python-curriculum#53]
There's lots of this happening:

![screen shot 2015-04-30 at 11 45 42](https://cloud.githubusercontent.com/assets/7372432/7411272/7df28da8-ef2e-11e4-9ead-8420ae6dbae5.png)

**Comment by andylolz** [comment]
This looks like the same problem as #38. There are indentation problems with these two lessons.

**Comment by andylolz** [comment]
Btw it took me ages to figure out the correct indentation. Pandoc is much fussier than github markdown, which will renders the current version just fine.

Here’s a sample, taken from https://github.com/CodeClub/python-curriculum/blob/d75ce546/en-GB/lessons/RPG/RPG.md:

+ If you edit the RPG.py file, you can see that the map is coded as a dictionary of rooms:

  ```python
  #a dictionary linking a room to other room positions
  rooms = {

              1 : {  "name"  : "Hall" ,
                     "south" : 2
                  } ,        

              2 : {  "name"  : "Kitchen" ,
                     "north" : 1
                  }

           }
  ```
