### ISSUE TITLE
Quiz question generator

### ISSUE THREAD

**Issue by dz0** [CodeClub/python-curriculum#55]
I have messy/poorly documented code for Moodle quiz  (random)  question generation https://code.google.com/p/algorithm-quiz/
You can try it  http://galvosukykla.lt/testai/ , for example 
- what will the program print (separate by spaces), http://galvosukykla.lt/testai/mod/quiz/view.php?id=9
- insert missing code. http://galvosukykla.lt/testai/mod/quiz/view.php?id=18
- errors http://galvosukykla.lt/testai/mod/quiz/attempt.php?attempt=70

Some question bank exports (in lithuanian) -- I could make it more i18 during summer.

**Comment by CodeClubRik** [comment]
Thanks for this, it sounds useful.
The moodle site requires a login to see the questions though :)

**Comment by dz0** [comment]
Login: demo
Pwd: Demo123*.  **(including dot)*

On Mon, May 18, 2015 at 12:53 PM, Rik <notifications@github.com> wrote:

> Thanks for this, it sounds useful.
> The moodle site requires a login to see the questions though :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CodeClub/python-curriculum/issues/55#issuecomment-103000194>
> .
>



-- 
Jurgis Pralgauskis
tel: 8-616 77613;
Don't worry, be happy and make things better ;)
http://galvosukykla.lt

**Comment by CodeClubRik** [comment]
Hi, this is great.
We've produced a similar quiz for evaluating the impact of our Scratch, HTML and Python projects, with multiple choice questions to assess the programming knowledge of a small sample of children. If we expand this quiz to all children and use it to assess impact long-term, it may be that we'll need to devise some more questions. I'll let you know how we get on, and maybe we could work together to devise a bank of questions.
Rik.
