### ISSUE TITLE
Python issues

### ISSUE THREAD

**Issue by JessD1989** [CodeClub/python-curriculum#58]
We’ve been doing a few of the activities under Python 1. One example that is in front of me is the RPG activity. I open the RPG.py file that has been already made and I get traceback errors. I am using Python 2.6.6 but this happens with Python 3 also. 

This also happens in other activities where my students have completed the their coding as per the instructions but they will get either syntax errors or similar traceback errors. 

We are using MacBooks running Yosemite.

Please see the attached images. 
![screen shot 2015-09-07 at 7 42 55 pm](https://cloud.githubusercontent.com/assets/12513135/9716606/4808372e-5563-11e5-909b-724caa742a04.png)
![screen shot 2015-09-07 at 7 43 20 pm](https://cloud.githubusercontent.com/assets/12513135/9716607/4813e3b2-5563-11e5-8d31-9a826603b588.png)

**Comment by CodeClubRik** [comment]
Hi @JessD1989 thanks for the feedback.

The RPG project should be run with Python 3. Is it possible to printscreen the error message you get when running the program in Python 3?

Thanks,
Rik.

**Comment by JessD1989** [comment]
all sorted. thanks rik!

**Comment by CodeClubRik** [comment]
That's great @JessD1989 - what was the issue? It would be useful to know how you fixed it, in case anyone else has a similar problem.
Rik.
