### ISSUE TITLE
Turtle Race: Change turtle names.

### ISSUE THREAD

**Issue by rik-cross** [CodeClub/python-curriculum#76]
At PyCon UK, a couple of children seemed to be confused by the following line:

```
red = Turtle()
red.color('red')
```

When changing colours, the children first tried changing the name of the turtle rather than the colour. Other children changed the colour of the turtle and ended up with:

```
red = Turtle()
red.color('purple')
```

As the turtle is named the same as the colour, changing the colours later on also requires the name of the turtle to be changed.

Should we give the turtles actual names, so that there's no confusion?

**Comment by tracygardner** [comment]
Yes, and giving them actual names is fun too.

**Comment by tracygardner** [comment]
We now have ada and bob. 8ec3fc84837c72128fbd298642b58adec1994ee7
