### ISSUE TITLE
RPG: Input validation needed

### ISSUE THREAD

**Issue by rik-cross** [CodeClub/python-curriculum#78]
Currently, the program fails when no input is given. This is because of the following line:

`move = move.lower().split()`

One possible fix is to delay splitting the input until there is something to split:

![screen shot 2016-09-14 at 14 34 00](https://cloud.githubusercontent.com/assets/18461167/18704299/56799ae2-7fe1-11e6-8171-2eacc86c08b7.png)

**Comment by martinpeck** [comment]
Alternatively, this...

``` python
if not move:
    continue
```

I also wonder if making your `if` statements into one (using if/elseif/else) would be better here, as you could then add an initial `if` block to check the state of `move` and handle this empty situation, as well as others where the command isn't know.

Probably far too advanced for this project would be to use a dictionary to implement a `switch` like structure.

**Comment by martinpeck** [comment]
tbh, given the audience (and the fact we're not trying to be super-pythonic but, instead, teach them the basics), what you said is also fine
