### ISSUE TITLE
Image missing in Popular Pets

### ISSUE THREAD

**Issue by tracygardner** [CodeClub/python-curriculum#79]
Example graph not showing in final challenge. 

https://www.codeclubprojects.org/en-GB/python/popular-pets/

**Comment by rik-cross** [comment]
Hi @tracygardner - is this the same image I fixed in https://github.com/CodeClub/python-curriculum/commit/0921016c1f5635ad3cf379c8156d5b6c905ef0de? The change isn't yet live, as the projects site needs to be rebuilt.

**Comment by tracygardner** [comment]
Probably then. I didn't realise it hadn't been rebuilt for that long.

**Comment by rik-cross** [comment]
Hey @tracygardner - There must've been 2 missing images, because I can still see that the image `pets-pn-bar.png` is referenced in the markdown but doesn't exist in the images folder.
