### ISSUE TITLE
Module 1, Project 4: Team Chooser - print TeamA

### ISSUE THREAD

**Issue by primaryicttech** [CodeClub/python-curriculum#83]
In step 2, there's a line of code which prints the contents of TeamA

![image](https://cloud.githubusercontent.com/assets/12617547/19152821/bbf14636-8bcb-11e6-96b1-cfaade569553.png)

This line then disappears in subsequent screenshots: 

![image](https://cloud.githubusercontent.com/assets/12617547/19152834/d4b47f26-8bcb-11e6-92ba-e78d61ce5bda.png)

But is then referenced in Step 3, as a line that can be copied and pasted: 

![image](https://cloud.githubusercontent.com/assets/12617547/19152859/ebeb03ae-8bcb-11e6-87f8-c2d0c0af9444.png)

As I had deleted it out thinking it was superfluous, I typed it back in instead, so not a huge problem - but some children might have also done this and be looking to copy and paste a line of code which isn't there?

**Comment by rik-cross** [comment]
@tracygardner We also had some feedback about the image `team-loop-finished.png`.

![screen shot 2016-11-11 at 11 27 36](https://cloud.githubusercontent.com/assets/18461167/20213700/e81f98a0-a801-11e6-9eea-a9c0de0d4e28.png)

The code in the image above should read `choice` and not `random.choice`. I haven't changed the image myself, as I didn't know if you'd spotted it when making the changes above.
